name: .NET Core

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install tools
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet paket restore
    - name: Build
      run: dotnet build --configuration Release

  publish_docker:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get tag name
        id: tag-name
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | sed 's/refs\/tags\///' -)"
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: telefragged/release-notes:${{ steps.tag-name.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  release_notes:
    runs-on: ubuntu-latest
    name: Create release notes
    needs: publish_docker
    steps:
    - name: Release notes step
      id: release-notes
      uses: telefragged/release-notes@0.1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        comment-issue: 'on'
